<tr class="<%evenodd%>">
  <td style="background: <%player.teamcolor%>; color: <%player.teamcolor%>;"><%player.teamid%>&#160;</td>
  <td><%player.name%></td>
  <td class="right"><%player.ranking%></td>
  <td class="right"><%player.score%></td>
  <td class="right"><%player.deaths%></td>
  <td class="right"><%player.kills%></td>
  <td class="right" title="Packet loss: <%player.packetloss%>"><%player.ping%></td>
  <td class="center"><%player.bot%></td>
  <td class="center"><%player.admin%></td>
  <td class="center"><%player.spectator%></td>
</tr>
